channels:
    - pytorch
    - conda-forge
name:
    adl-course
dependencies:
    - cpuonly
    - imageio
    - jupyter
    - nb_conda
    - pytorch
    - scikit-image
    - scikit-learn
    - tensorboard
    - torchvision
    - tqdm
